language: php
php:
  - '5.5'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - php run-selenium-server.php
  - sleep 30

  - composer self-update
  - composer install


script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run acceptance