language: php
php:
  - '5.5'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - composer self-update
  - composer install

  - sudo apt-get update && sudo apt install oracle-java8-set-default
  - java -version
  - sudo apt-get install firefox

  - php run-selenium-server.php &
  - sleep 30


script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run acceptance